### ISSUE TITLE
comparison with previous art

### ISSUE THREAD

**Issue by Turlan** [JDAI-CV/FADA#1]
Thanks for your work ! I am curious about the difference of this paper with previous methods for category-wise feature alignment in idea level. 

For example, [Chen et al. ICCV'17](https://arxiv.org/pdf/1704.08509.pdf) proposed to align the feature distribution with global and class-wise discriminator. The loss defined at eqution 9) in their paper is quite similar with your proposed loss. Besides, [Du et al. ICCV'19](https://openaccess.thecvf.com/content_ICCV_2019/papers/Du_SSF-DAN_Separated_Semantic_Feature_Based_Domain_Adaptation_Network_for_Semantic_ICCV_2019_paper.pdf) also adapts similar idea without global alignment.

Despite of some different implementation details, could you explain the main differences between your proposed method and the mentioned two paper?

**Comment by krumo** [comment]
Thanks for your interest! This is a good question. 

Firstly, both [Chen et al. ICCV'17](https://arxiv.org/pdf/1704.08509.pdf) and [Du et al. ICCV'19](https://openaccess.thecvf.com/content_ICCV_2019/papers/Du_SSF-DAN_Separated_Semantic_Feature_Based_Domain_Adaptation_Network_for_Semantic_ICCV_2019_paper.pdf) perform a grid-level class-wise alignment, but our method strives to align features at a pixel-level. 

Plus, both works utilize independent discriminators for different categories and employ an adaptive weight constructed from network predictions, while our method proposes a single and consistent fine-grained discriminator which could recognize the domain and class-level information together. The domain encodings extracted from the network prediction will directly guide the discriminator's training and confusion. We believe our method could preserve the class-level information during confusion step and produce better domain-invariant discriminative features.
