### ISSUE TITLE
About multi-scale testing?

### ISSUE THREAD

**Issue by happyzhouch** [JDAI-CV/FADA#12]
Have you released the code to implement multi-scale testing? I cannot find the implementation of multi-scale testing in 'test.py'. Can you tell me how to achieve it or find it in your code?

**Comment by krumo** [comment]
Hi, the multi-scale testing is implemented at [here](https://github.com/JDAI-CV/FADA/blob/a1c6403963184a3427eda68cc94b03ff6143368a/test.py#L46).
