### ISSUE TITLE
why don't you set one more label with name "others" for labels in cityscapes which do not exist in GTA5 or Sythia ?

### ISSUE THREAD

**Issue by taintpro98** [JDAI-CV/FADA#13]
why do you set one more label with name "others" for labels in cityscapes which do not exist in GTA5 or Sythia ?

**Comment by taintpro98** [comment]
Sorry, I mean why don't you set one more label with name "others" for labels in cityscapes which do not exist in GTA5 or Sythia ?

**Comment by krumo** [comment]
Hi, thanks for your interest!

The way we process lables in Cityscapes follows previous works. We didn't test whether using one more label could contribute to the final performance. You are always welcomed to share your results!

**Comment by taintpro98** [comment]
thanks for your answer. Moreover, I found out that train_src and train_self_distill are the same. I have not tried train_self_distill, but that's weird when your model achieved higher performance as 49.2 > 46.9

**Comment by krumo** [comment]
The main difference between train_src and train_self_distill is that the former is trained on GTA5 dataset, while the latter is trained on Cityscapes train set with pseudo labels we generate.
