### ISSUE TITLE
About LICENSE

### ISSUE THREAD

**Issue by yukkyo** [JDAI-CV/FADA#2]
@krumo 
Thanks for sharing excellent code!
I'm curious what the license for this code is.
Because I'm thinking of using it in competitions like Kaggle.

**Comment by krumo** [comment]
Hi, @yukkyo . Thanks for your attention! A licence file has been uploaded. Feel free to use this repo for your Kaggle competitions.

**Comment by yukkyo** [comment]
Hi @krumo .
Thanks for the lightning response!!
