### ISSUE TITLE
train custom dataset

### ISSUE THREAD

**Issue by zhou-rui1** [JDAI-CV/FADA#20]
Hi, how to train my own dataset without label_info.p,  I have the images and labels for binary seg.

Any guidance will be so helpful!

**Comment by krumo** [comment]
Hi, for training on your custom dataset, you could consider to modify [gta5.py](https://github.com/JDAI-CV/FADA/blob/master/core/datasets/gta5.py) for source domain and [cityscapes.py](https://github.com/JDAI-CV/FADA/blob/master/core/datasets/cityscapes.py) for target domain. For training without label statistics file, you could consider to remove [Line 34](https://github.com/JDAI-CV/FADA/blob/a1c6403963184a3427eda68cc94b03ff6143368a/core/datasets/gta5.py#L34)-[Line 62](https://github.com/JDAI-CV/FADA/blob/a1c6403963184a3427eda68cc94b03ff6143368a/core/datasets/gta5.py#L62) in [gta5.py](https://github.com/JDAI-CV/FADA/blob/master/core/datasets/gta5.py).

**Comment by zhou-rui1** [comment]
Thanks for reply,
 
then how to assign `self.img_ids` directly from the images name?

and I just have 2 classes , for `self.id_to_trainid = {7: 0, 8: 1...}`  how to change `7，8`？

**Comment by krumo** [comment]
Hi, I utilize `data_list` files like [cityscapes_train_list.txt](https://github.com/JDAI-CV/FADA/blob/master/datasets/cityscapes_train_list.txt) to store the paths of training data and test data. The `self.img_ids` is constructed by reading filename in `data_list` file. The path of dataset and `data_list` file is defined in [dataset_path_catalog.py](https://github.com/JDAI-CV/FADA/blob/master/core/datasets/dataset_path_catalog.py). 

I defined a `self.id_to_trainid` because I trained the model with a subset of labels defined in GTA5 and Cityscapes dataset. If you just have two classes, you could just define `self.id_to_trainid={0:0, 1:1}`.

**Comment by zhou-rui1** [comment]
Thanks for your patient guidance,

but it seems to not work with the binary mask, 

I comment the `ignore_label`  and load the label like this ` label = np.array(Image.open(datafiles["label"]),dtype=np.uint8)`
 
`/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py:365: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Traceback (most recent call last):
  File "train_src.py", line 314, in <module>
    main()
  File "train_src.py", line 307, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "train_src.py", line 139, in train
    loss = criterion(pred, src_label)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py", line 1042, in __init__
    super(CrossEntropyLoss, self).__init__(weight, size_average, reduce, reduction)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py", line 25, in __init__
    super(_WeightedLoss, self).__init__(size_average, reduce, reduction)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/loss.py", line 18, in __init__
    self.reduction = _Reduction.legacy_get_string(size_average, reduce)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/_reduction.py", line 35, in legacy_get_string
    if size_average and reduce:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous`

should I assign map class for my dataset?

**Comment by krumo** [comment]
That's weird. This error is usually caused by the wrong use of CrossEntropyLoss. Please check whether it is caused by binary mask.
