### ISSUE TITLE
Soft labels or hard labels at self distillation training ?

### ISSUE THREAD

**Issue by taintpro98** [JDAI-CV/FADA#21]
at the self distillation phase, you saved the pseudo labels as hard labels instead of soft ones. Why did you name the folder soft_labels ?

**Comment by LeopoldACC** [comment]
> at the self distillation phase, you saved the pseudo labels as hard labels instead of soft ones. Why did you name the folder soft_labels ?
 
Hi, @krumo .I have the same question with him,and I have another question is about the threshold selection of [0.7,0.8,0.9,1.0] in your paper.I just find the argmax() be used in generating pseudo labels.

**Comment by krumo** [comment]
Hi, sorry for the late reply. Initially we tried saving soft labels in the disk to perform self-distillation. However, we soon found that it would add a huge burden to the disk storage and it didn't give a better performance compared to hard labels. Thus, in the release code we choose to store the labels in hard labels format, while we forget to change the folder's name. If you believe this naming is too confusing, I would rename this folder.

@LeopoldACC For your question, the thresholding is not performed at pseudo labels generation. As mentioned in the paper, the thresholding occurs when adversarial training is performed. Specifically, you could find the usage of thresholding [here](https://github.com/JDAI-CV/FADA/blob/a1c6403963184a3427eda68cc94b03ff6143368a/train_adv.py#L187).
