### ISSUE TITLE
Do I need add torch.distributed.barrier() in test ?

### ISSUE THREAD

**Issue by desti-nation** [JDAI-CV/FADA#25]
do I need to add `torch.distributed.barrier()`
before https://github.com/JDAI-CV/FADA/blob/master/train_src.py#L233

**Comment by krumo** [comment]
Hi, thanks for this question. Yes, I think there should be a `torch.distributed.barrier()` here. It is interesting that I didn't encounter any errors without this `torch.distributed.barrier()`.
