### ISSUE TITLE
Freeze discriminator parameters before performing  adversarial loss backward

### ISSUE THREAD

**Issue by daofeng2007** [JDAI-CV/FADA#26]
Should not the parameters of discriminators be frozen before applying  loss_adv_tgt.backward()? The purpose here is to only adjust the parameters of the feature extractor to make the target feature more similar to the source feature. Therefore, I think the discriminator should be frozen before applying loss_adv_tgt.backward() in LN 193 in train_adv.py. file.

**Comment by krumo** [comment]
Hi, thanks for your interest! 

When performing  adversarial loss, the discriminator would remain unchanged. 

As I defined `optimizer_fea` and `optimizer_cls` to only optimize `feature_extractor.parameters()` and `classifier.parameters()` respectively at [LN79-83](https://github.com/JDAI-CV/FADA/blob/a1c6403963184a3427eda68cc94b03ff6143368a/train_adv.py#L79), when backpropogate adversarial loss at [LN193](https://github.com/JDAI-CV/FADA/blob/a1c6403963184a3427eda68cc94b03ff6143368a/train_adv.py#L193), the gradient on feature extractor and discriminator will be computed, while only feature extractor would be updated.

**Comment by daofeng2007** [comment]
Thank you for the explainazation. That makes sense!
