### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by adricarda** [JDAI-CV/FADA#3]
Hi, thank you for your work and for releasing the code! It is quite interesting since it is considerably different from recent techniques. I was wondering if you can release the pretrained weights for FADA without the self-distillation step. It would be interesting to build from this step since Self-Distillation is a general strategy that can be applied to any model.
Thanks in advance.

**Comment by krumo** [comment]
Thank you for your suggestion! The pre-trained models without the self-distillation step have been released.
