### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zang5xixi** [JDAI-CV/FADA#4]
I recently read this paper, and there is a problem I didn't figure out. How to calculate **μ**i in the CCD formula? Is it to use source samples or source samples and target samples?

**Comment by krumo** [comment]
Hi @zang5xixi,
Thanks for your interest. In the paper we use both source and target samples to compute a global class center μi.

**Comment by zang5xixi** [comment]
> 
> 
> I recently read this paper, and there is a problem I didn't figure out. How to calculate **μ**i in the CCD formula? Is it to use source samples or source samples and target samples?



> 
> 
> Hi @zang5xixi,
> Thanks for your interest. In the paper we use both source and target samples to compute a global class center μi.

thank you for your reply. I would also like to ask, do you still keep the CCD of AdaptSegNet and CLAN in each category?

**Comment by krumo** [comment]
Hi @zang5xixi, I follow the same way to compute CCD for AdaptSegNet and CLAN using their provided pre-trained model on GTA5->Cityscapes task.

**Comment by zang5xixi** [comment]
> 
> 
> Hi @zang5xixi, I follow the same way to compute CCD for AdaptSegNet and CLAN using their provided pre-trained model on GTA5->Cityscapes task.

Thank you very much~
