### ISSUE TITLE
About Cross-City?

### ISSUE THREAD

**Issue by BinhuiXie** [JDAI-CV/FADA#6]
Hi! Great work! 
I have a quick question: when I conduct adaptation between real images from different cities, i.e., Cityscapes to Cross-City, but becaues the Cross-City only defines 13 major classes for annotations, should I set `NUM_CLASSES=13` and adjust the `id_to_trained` in dataset or leave it unchanged and then report the results of the shared 13 classes?

Thanks in advance
binhui

**Comment by krumo** [comment]
Hi, I trained the model with `NUM_CLASSES=19` when performing Cityscapes to Cross-City and reported the results of Cross-City's 13 classes.
