### ISSUE TITLE
SYNTHIA model evaluation

### ISSUE THREAD

**Issue by JuiChang** [JDAI-CV/FADA#7]
Hi! Thanks for sharing the work!

Because in the paper, the result is not reported. Want to make sure that, to evaluate the given SYNTHIA model without self distillation&MST (s2c_adv.pth) is configs/deeplabv2_r101_adv_synthia.yaml the correct yaml argument for running test.py? the result mIoU is 0.4091

Thanks.

**Comment by krumo** [comment]
Hi @JuiChang , thanks for your interest! 
Yes, configs/deeplabv2_r101_adv_synthia.yaml is the correct yaml for evaluating s2c_adv.pth. Your result is the same with my record.
