### ISSUE TITLE
How do you use thresholds in your code？

### ISSUE THREAD

**Issue by ALEX13679173326** [JDAI-CV/FADA#9]
Good job!However,I have some questions.
As mentioned in the paper, soft labels are also filtered by the threshold. In the code, I only see this:
       tgt_soft_label[tgt_soft_label>0.9] = 0.9
Please explain this code.Why don't you filter out confidence lower than the threshold.

**Comment by krumo** [comment]
Hi, thanks for your interest!
As you see in the code, `src_soft_label[src_soft_label>0.9] = 0.9` and `tgt_soft_label[tgt_soft_label>0.9] = 0.9` refers to our confidence clipping strategy in the paper. I believe the motivation and the effectiveness of this strategy have been clearly stated in the paper's section 4.6. Please let me know if you have any further specific questions.
